RUN mkdir /site
COPY appli_liste /site
WORKDIR /site
EXPOSE 8080
CMD python -m http.server 8080

LABEL author.groupe="groupe_5"
LABEL description="réalisé dans le cadre d'un projet"
LABEL author.name1="Fatoumata binta Barry"
LABEL author.name2="Mariama Djelo Barry"
LABEL author.name3="CAMARA Ismael"
LABEL author.name4="Intissame ANDHUM"
LABEL author.email="groupedevops05@gmail.com"